# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code_files\Qt\Sudoku-GUI-v1\gameover.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameOverDialog(object):
    def setupUi(self, GameOverDialog):
        GameOverDialog.setObjectName("GameOverDialog")
        GameOverDialog.setWindowModality(QtCore.Qt.NonModal)
        GameOverDialog.resize(400, 315)
        GameOverDialog.setAutoFillBackground(False)
        GameOverDialog.setStyleSheet("background-color:#ffffff")
        GameOverDialog.setSizeGripEnabled(False)
        GameOverDialog.setModal(False)
        self.label = QtWidgets.QLabel(GameOverDialog)
        self.label.setGeometry(QtCore.QRect(100, 30, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.errorLabel = QtWidgets.QLabel(GameOverDialog)
        self.errorLabel.setGeometry(QtCore.QRect(70, 90, 260, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color:#8c8c8c")
        self.errorLabel.setObjectName("errorLabel")
        self.restoreBtn = QtWidgets.QPushButton(GameOverDialog)
        self.restoreBtn.setGeometry(QtCore.QRect(29, 150, 351, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.restoreBtn.setFont(font)
        self.restoreBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: #0072E3;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #006dd3;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #005eb6;\n"
"}")
        self.restoreBtn.setFlat(True)
        self.restoreBtn.setObjectName("restoreBtn")
        self.newBtn = QtWidgets.QPushButton(GameOverDialog)
        self.newBtn.setGeometry(QtCore.QRect(30, 230, 351, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newBtn.setFont(font)
        self.newBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: #ffffff;\n"
"    color: #0072E3;\n"
"}\n"
"QPushButton:hover {;\n"
"    text-decoration: underline; \n"
"    color: #0072E3;\n"
"}\n"
"")
        self.newBtn.setFlat(True)
        self.newBtn.setObjectName("newBtn")

        self.retranslateUi(GameOverDialog)
        QtCore.QMetaObject.connectSlotsByName(GameOverDialog)

    def retranslateUi(self, GameOverDialog):
        _translate = QtCore.QCoreApplication.translate
        GameOverDialog.setWindowTitle(_translate("GameOverDialog", "Dialog"))
        self.label.setText(_translate("GameOverDialog", "游戏结束"))
        self.errorLabel.setText(_translate("GameOverDialog", "你出现了3个错误，游戏失败"))
        self.restoreBtn.setText(_translate("GameOverDialog", "第二次机会"))
        self.newBtn.setText(_translate("GameOverDialog", "新游戏"))
import icons_rc
