# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code_files\Qt\Sudoku-GUI-v1\hint.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HintDialog(object):
    def setupUi(self, HintDialog):
        HintDialog.setObjectName("HintDialog")
        HintDialog.resize(320, 210)
        HintDialog.setStyleSheet("background-color:rgb(244, 244, 244)")
        self.label = QtWidgets.QLabel(HintDialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.hintLabel = QtWidgets.QLabel(HintDialog)
        self.hintLabel.setGeometry(QtCore.QRect(30, 60, 260, 75))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hintLabel.setFont(font)
        self.hintLabel.setStyleSheet("color:#8c8c8c")
        self.hintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hintLabel.setObjectName("hintLabel")
        self.progressLabel_1 = QtWidgets.QLabel(HintDialog)
        self.progressLabel_1.setGeometry(QtCore.QRect(140, 170, 10, 10))
        self.progressLabel_1.setStyleSheet("border-radius:5px;\n"
"background-color:#a8a8a8")
        self.progressLabel_1.setText("")
        self.progressLabel_1.setObjectName("progressLabel_1")
        self.progressLabel_2 = QtWidgets.QLabel(HintDialog)
        self.progressLabel_2.setGeometry(QtCore.QRect(170, 170, 10, 10))
        self.progressLabel_2.setStyleSheet("border-radius:5px;\n"
"background-color:#a8a8a8")
        self.progressLabel_2.setText("")
        self.progressLabel_2.setObjectName("progressLabel_2")
        self.rightToolButton = QtWidgets.QToolButton(HintDialog)
        self.rightToolButton.setGeometry(QtCore.QRect(240, 150, 50, 50))
        self.rightToolButton.setStyleSheet("QToolButton {\n"
"    border-radius: 25px;\n"
"    background-color: #EAEEF4;\n"
"    color: rgb(85, 170, 255);\n"
"}\n"
"QToolButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QToolButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightToolButton.setIcon(icon)
        self.rightToolButton.setIconSize(QtCore.QSize(25, 25))
        self.rightToolButton.setObjectName("rightToolButton")
        self.leftToolButton = QtWidgets.QToolButton(HintDialog)
        self.leftToolButton.setGeometry(QtCore.QRect(30, 150, 50, 50))
        self.leftToolButton.setStyleSheet("QToolButton {\n"
"    border-radius: 25px;\n"
"    background-color: #EAEEF4;\n"
"    color: rgb(85, 170, 255);\n"
"}\n"
"QToolButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QToolButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftToolButton.setIcon(icon1)
        self.leftToolButton.setIconSize(QtCore.QSize(25, 25))
        self.leftToolButton.setObjectName("leftToolButton")
        self.okToolButton = QtWidgets.QToolButton(HintDialog)
        self.okToolButton.setGeometry(QtCore.QRect(240, 150, 50, 50))
        self.okToolButton.setStyleSheet("QToolButton {\n"
"    border-radius: 25px;\n"
"    background-color: #EAEEF4;\n"
"    color: rgb(85, 170, 255);\n"
"}\n"
"QToolButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QToolButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okToolButton.setIcon(icon2)
        self.okToolButton.setIconSize(QtCore.QSize(25, 25))
        self.okToolButton.setObjectName("okToolButton")

        self.retranslateUi(HintDialog)
        QtCore.QMetaObject.connectSlotsByName(HintDialog)

    def retranslateUi(self, HintDialog):
        _translate = QtCore.QCoreApplication.translate
        HintDialog.setWindowTitle(_translate("HintDialog", "Dialog"))
        self.label.setText(_translate("HintDialog", "最后剩余的单元格"))
        self.hintLabel.setText(_translate("HintDialog", "留意这个单元格及突出显示区域"))
        self.rightToolButton.setText(_translate("HintDialog", "..."))
        self.leftToolButton.setText(_translate("HintDialog", "..."))
        self.okToolButton.setText(_translate("HintDialog", "..."))
import icons_rc
