# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code_files\Qt\Sudoku-GUI-v1\new_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewGameDialog(object):
    def setupUi(self, NewGameDialog):
        NewGameDialog.setObjectName("NewGameDialog")
        NewGameDialog.resize(350, 530)
        self.label = QtWidgets.QLabel(NewGameDialog)
        self.label.setGeometry(QtCore.QRect(75, 20, 200, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewGameDialog)
        self.label_2.setGeometry(QtCore.QRect(75, 60, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#8c8c8c")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.easyBtn = QtWidgets.QPushButton(NewGameDialog)
        self.easyBtn.setGeometry(QtCore.QRect(20, 110, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.easyBtn.setFont(font)
        self.easyBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.easyBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/sudoku.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.easyBtn.setIcon(icon)
        self.easyBtn.setIconSize(QtCore.QSize(40, 40))
        self.easyBtn.setFlat(True)
        self.easyBtn.setObjectName("easyBtn")
        self.normalBtn = QtWidgets.QPushButton(NewGameDialog)
        self.normalBtn.setGeometry(QtCore.QRect(20, 166, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.normalBtn.setFont(font)
        self.normalBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.normalBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        self.normalBtn.setIcon(icon)
        self.normalBtn.setIconSize(QtCore.QSize(40, 40))
        self.normalBtn.setFlat(True)
        self.normalBtn.setObjectName("normalBtn")
        self.line = QtWidgets.QFrame(NewGameDialog)
        self.line.setGeometry(QtCore.QRect(20, 165, 311, 3))
        self.line.setStyleSheet("color:rgb(144, 144, 144)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hardBtn = QtWidgets.QPushButton(NewGameDialog)
        self.hardBtn.setGeometry(QtCore.QRect(20, 222, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.hardBtn.setFont(font)
        self.hardBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hardBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        self.hardBtn.setIcon(icon)
        self.hardBtn.setIconSize(QtCore.QSize(40, 40))
        self.hardBtn.setFlat(True)
        self.hardBtn.setObjectName("hardBtn")
        self.line_2 = QtWidgets.QFrame(NewGameDialog)
        self.line_2.setGeometry(QtCore.QRect(20, 221, 311, 3))
        self.line_2.setStyleSheet("color:rgb(144, 144, 144)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(NewGameDialog)
        self.line_3.setGeometry(QtCore.QRect(20, 277, 311, 3))
        self.line_3.setStyleSheet("color:rgb(144, 144, 144)")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.perfessionalBtn = QtWidgets.QPushButton(NewGameDialog)
        self.perfessionalBtn.setGeometry(QtCore.QRect(20, 278, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.perfessionalBtn.setFont(font)
        self.perfessionalBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.perfessionalBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        self.perfessionalBtn.setIcon(icon)
        self.perfessionalBtn.setIconSize(QtCore.QSize(40, 40))
        self.perfessionalBtn.setFlat(True)
        self.perfessionalBtn.setObjectName("perfessionalBtn")
        self.extremeBtn = QtWidgets.QPushButton(NewGameDialog)
        self.extremeBtn.setGeometry(QtCore.QRect(20, 334, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.extremeBtn.setFont(font)
        self.extremeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.extremeBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        self.extremeBtn.setIcon(icon)
        self.extremeBtn.setIconSize(QtCore.QSize(40, 40))
        self.extremeBtn.setFlat(True)
        self.extremeBtn.setObjectName("extremeBtn")
        self.line_4 = QtWidgets.QFrame(NewGameDialog)
        self.line_4.setGeometry(QtCore.QRect(20, 333, 311, 3))
        self.line_4.setStyleSheet("color:rgb(144, 144, 144)")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(NewGameDialog)
        self.line_5.setGeometry(QtCore.QRect(20, 389, 311, 3))
        self.line_5.setStyleSheet("color:rgb(144, 144, 144)")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.cancelBtn = QtWidgets.QPushButton(NewGameDialog)
        self.cancelBtn.setGeometry(QtCore.QRect(20, 460, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        self.cancelBtn.setIconSize(QtCore.QSize(35, 35))
        self.cancelBtn.setFlat(True)
        self.cancelBtn.setObjectName("cancelBtn")
        self.restartBtn = QtWidgets.QPushButton(NewGameDialog)
        self.restartBtn.setGeometry(QtCore.QRect(20, 390, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.restartBtn.setFont(font)
        self.restartBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.restartBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: #e3e6ec;\n"
"    color: #0072e3;\n"
"    text-align:left;\n"
"    padding-left: 18px;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #dce0e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cdd0d5;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartBtn.setIcon(icon1)
        self.restartBtn.setIconSize(QtCore.QSize(25, 25))
        self.restartBtn.setFlat(True)
        self.restartBtn.setObjectName("restartBtn")

        self.retranslateUi(NewGameDialog)
        QtCore.QMetaObject.connectSlotsByName(NewGameDialog)

    def retranslateUi(self, NewGameDialog):
        _translate = QtCore.QCoreApplication.translate
        NewGameDialog.setWindowTitle(_translate("NewGameDialog", "Dialog"))
        self.label.setText(_translate("NewGameDialog", "选择游戏模式"))
        self.label_2.setText(_translate("NewGameDialog", "当前游戏进度将丢失"))
        self.easyBtn.setText(_translate("NewGameDialog", "简单"))
        self.normalBtn.setText(_translate("NewGameDialog", "中等"))
        self.hardBtn.setText(_translate("NewGameDialog", "困难"))
        self.perfessionalBtn.setText(_translate("NewGameDialog", "专家"))
        self.extremeBtn.setText(_translate("NewGameDialog", "地狱"))
        self.cancelBtn.setText(_translate("NewGameDialog", "取消"))
        self.restartBtn.setText(_translate("NewGameDialog", " 重新开始"))
import icons_rc
