# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code_files\Qt\Sudoku-GUI-v1\new_game_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewGameConfirmDialog(object):
    def setupUi(self, NewGameConfirmDialog):
        NewGameConfirmDialog.setObjectName("NewGameConfirmDialog")
        NewGameConfirmDialog.resize(400, 223)
        NewGameConfirmDialog.setStyleSheet("background-color:white;")
        NewGameConfirmDialog.setModal(True)
        self.label_3 = QtWidgets.QLabel(NewGameConfirmDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 30, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(NewGameConfirmDialog)
        self.label_4.setGeometry(QtCore.QRect(100, 70, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#8c8c8c")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.okButton = QtWidgets.QPushButton(NewGameConfirmDialog)
        self.okButton.setGeometry(QtCore.QRect(20, 120, 170, 50))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #0072E3;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #006dd3;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #005eb6;\n"
"}")
        self.okButton.setFlat(True)
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(NewGameConfirmDialog)
        self.cancelButton.setGeometry(QtCore.QRect(210, 120, 170, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"    color: #646464;\n"
"    border:1px solid #8c8c8c\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #e5e5e5;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #cbcbcb;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.cancelButton.setFlat(True)
        self.cancelButton.setObjectName("cancelButton")
        self.checkBox = QtWidgets.QCheckBox(NewGameConfirmDialog)
        self.checkBox.setGeometry(QtCore.QRect(150, 180, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(NewGameConfirmDialog)
        QtCore.QMetaObject.connectSlotsByName(NewGameConfirmDialog)

    def retranslateUi(self, NewGameConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        NewGameConfirmDialog.setWindowTitle(_translate("NewGameConfirmDialog", "Dialog"))
        self.label_3.setText(_translate("NewGameConfirmDialog", "开始新游戏"))
        self.label_4.setText(_translate("NewGameConfirmDialog", "当前游戏进度将丢失"))
        self.okButton.setText(_translate("NewGameConfirmDialog", "ok"))
        self.cancelButton.setText(_translate("NewGameConfirmDialog", "cancel"))
        self.checkBox.setText(_translate("NewGameConfirmDialog", "不再询问"))
