# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code_files\Qt\Sudoku-GUI-v1\vectory.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vectoryDialog(object):
    def setupUi(self, vectoryDialog):
        vectoryDialog.setObjectName("vectoryDialog")
        vectoryDialog.resize(400, 310)
        vectoryDialog.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(vectoryDialog)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 200, 55))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#0072E3")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(vectoryDialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/res/Level.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(vectoryDialog)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#0072E3")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.levelLabel = QtWidgets.QLabel(vectoryDialog)
        self.levelLabel.setGeometry(QtCore.QRect(310, 90, 45, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.levelLabel.setFont(font)
        self.levelLabel.setStyleSheet("color:#0072E3")
        self.levelLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.levelLabel.setObjectName("levelLabel")
        self.line = QtWidgets.QFrame(vectoryDialog)
        self.line.setGeometry(QtCore.QRect(90, 140, 255, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(vectoryDialog)
        self.label_5.setGeometry(QtCore.QRect(90, 160, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#0072E3")
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(vectoryDialog)
        self.label_6.setGeometry(QtCore.QRect(50, 170, 30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/res/timer.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.timerLabel = QtWidgets.QLabel(vectoryDialog)
        self.timerLabel.setGeometry(QtCore.QRect(305, 160, 45, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.timerLabel.setFont(font)
        self.timerLabel.setStyleSheet("color:#0072E3")
        self.timerLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.timerLabel.setObjectName("timerLabel")
        self.NewBtn = QtWidgets.QPushButton(vectoryDialog)
        self.NewBtn.setGeometry(QtCore.QRect(50, 220, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.NewBtn.setFont(font)
        self.NewBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: #0072E3;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {;\n"
"    background-color: #006dd3;\n"
"}\n"
"QPushButton:pressed {;\n"
"    background-color: #005eb6;\n"
"}")
        self.NewBtn.setFlat(True)
        self.NewBtn.setObjectName("NewBtn")

        self.retranslateUi(vectoryDialog)
        QtCore.QMetaObject.connectSlotsByName(vectoryDialog)

    def retranslateUi(self, vectoryDialog):
        _translate = QtCore.QCoreApplication.translate
        vectoryDialog.setWindowTitle(_translate("vectoryDialog", "Dialog"))
        self.label_2.setText(_translate("vectoryDialog", "太棒了"))
        self.label_3.setText(_translate("vectoryDialog", "难度"))
        self.levelLabel.setText(_translate("vectoryDialog", "简单"))
        self.label_5.setText(_translate("vectoryDialog", "Time"))
        self.timerLabel.setText(_translate("vectoryDialog", "05:10"))
        self.NewBtn.setText(_translate("vectoryDialog", "New Game"))
import icons_rc
